import { afterAll, beforeAll, beforeEach, expect, it, vi } from "vitest";
import { fixtureAttempt, fixtureSession } from "./attempt-fixtures";
import { type PaymentAttempt, decodeAttempt } from "./attempt-terms";

const mocks = vi.hoisted(() => ({
  attempt: null as PaymentAttempt | null,
  create: vi.fn(),
  retrieve: vi.fn(),
  saveFails: false,
}));
vi.mock("./stripe", () => ({
  createCheckoutSession: mocks.create,
  retrieveSession: mocks.retrieve,
  retrieveConnectStatus: vi.fn(),
}));
vi.mock("@dayotter/db", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@dayotter/db")>();
  const update = () => ({
    set: (fields: object) => ({
      where: () => ({
        returning: async () => {
          if (mocks.saveFails) throw new Error("database response lost");
          Object.assign(mocks.attempt!, fields);
          return [mocks.attempt];
        },
      }),
    }),
  });
  const tx = {
    select: () => ({ from: () => ({ where: () => ({ for: async () => [mocks.attempt] }) }) }),
    update,
  };
  return {
    ...actual,
    getDb: () => ({ transaction: async (fn: (tx: unknown) => unknown) => fn(tx), update }),
  };
});
import { appointmentCheckout, bindAttemptSession } from "./attempts";

const previousKey = process.env.ENCRYPTION_KEY;
beforeAll(() => {
  process.env.ENCRYPTION_KEY = "ab".repeat(32);
});
afterAll(() => {
  if (previousKey === undefined) Reflect.deleteProperty(process.env, "ENCRYPTION_KEY");
  else process.env.ENCRYPTION_KEY = previousKey;
});
beforeEach(() => {
  vi.clearAllMocks();
  mocks.attempt = fixtureAttempt();
  mocks.saveFails = false;
});

it("recovers a Session accepted before local response persistence failed using identical parameters/key", async () => {
  const attempt = mocks.attempt!;
  // Fresh deadlines are persisted once, never regenerated by a retry.
  attempt.createdAt = new Date();
  attempt.creationDeadline = new Date(Date.now() + 900000);
  attempt.expiresAt = new Date(Math.floor(Date.now() / 1000) * 1000 + 7200000);
  const session = fixtureSession(attempt);
  mocks.create.mockResolvedValue({ id: session.id, url: session.url, session });
  mocks.saveFails = true;
  await expect(appointmentCheckout(attempt)).rejects.toThrow("database response lost");
  expect(attempt.checkoutSessionId).toBeNull();
  mocks.saveFails = false;
  await expect(appointmentCheckout(attempt)).resolves.toEqual({ checkoutUrl: session.url });
  expect(mocks.create.mock.calls[0]).toEqual(mocks.create.mock.calls[1]);
  expect(mocks.create.mock.calls[0]![0]).toMatchObject({
    idempotencyKey: `appointment-checkout:${attempt.id}:v1`,
    amount: 3500,
    metadata: { attemptId: attempt.id, quoteHash: attempt.quoteHash },
    expiresAt: Math.floor(attempt.expiresAt.getTime() / 1000),
  });
  expect(attempt.checkoutSessionId).toBe(session.id);
});

it("retrieves an existing Session using original routing and never creates another checkout", async () => {
  const attempt = mocks.attempt!;
  attempt.state = "open";
  attempt.checkoutSessionId = "cs_saved";
  attempt.checkoutUrl = "https://checkout.example.test/saved";
  const session = fixtureSession(attempt);
  mocks.retrieve.mockResolvedValue(session);
  await expect(appointmentCheckout(attempt)).resolves.toEqual({ checkoutUrl: session.url });
  expect(mocks.retrieve).toHaveBeenCalledWith("cs_saved", decodeAttempt(attempt).route);
  expect(mocks.create).not.toHaveBeenCalled();
});

it("records verified expiration without replacing the intent or Session", async () => {
  const attempt = mocks.attempt!;
  attempt.state = "open";
  attempt.checkoutSessionId = "cs_saved";
  mocks.retrieve.mockResolvedValue({ ...fixtureSession(attempt), status: "expired", url: null });
  await expect(appointmentCheckout(attempt)).rejects.toThrow("expired");
  expect(attempt.state).toBe("expired");
  expect(mocks.create).not.toHaveBeenCalled();
});

it("will not bind a second Session or wrong amount to an immutable attempt", async () => {
  const attempt = mocks.attempt!;
  attempt.checkoutSessionId = "cs_saved";
  await expect(
    bindAttemptSession(attempt, { ...fixtureSession(attempt), id: "cs_another" }),
  ).rejects.toThrow("saved checkout terms");
  await expect(
    bindAttemptSession(attempt, { ...fixtureSession(attempt), amount_total: 1 }),
  ).rejects.toThrow("saved checkout terms");
  expect(attempt.checkoutSessionId).toBe("cs_saved");
});
